version: "3.9"

services:
  bugtracker-backend:
    image: ${AZURE_WEBAPP_IMAGE}
    restart: always
    environment:
      BUGTRACKER_APP_ENV: production
      BUGTRACKER_STORE_BACKEND: mongodb
      BUGTRACKER_JWT_SECRET_KEY: ${BUGTRACKER_JWT_SECRET_KEY}
      BUGTRACKER_MONGODB_URI: ${BUGTRACKER_MONGODB_URI}
      BUGTRACKER_MONGODB_DB_NAME: ${BUGTRACKER_MONGODB_DB_NAME}
      BUGTRACKER_CORS_ORIGINS: ${BUGTRACKER_CORS_ORIGINS}
      BUGTRACKER_AZURE_BLOB_CONNECTION_STRING: ${BUGTRACKER_AZURE_BLOB_CONNECTION_STRING}
      BUGTRACKER_AZURE_BLOB_CONTAINER_NAME: ${BUGTRACKER_AZURE_BLOB_CONTAINER_NAME}
    ports:
      - "8000:8000"
